warnings_are_errors: false
language: node_js
node_js:
    - 10.8.0
cache:
    directories:
        - node_modules
branches:
    only:
        - master
script:
    - yarn test
deploy:
    provider: heroku
    verbose: true
    api_key:
        secure: iDqmE7CC/QWmGsh+CoWPRxOtMHhluDdE9JNRB6uTY8HV7IMklyHxejG/xc1X1o2RU6tFOdCQvLy5dP0JltyjjqobGY8+q8LfXGl2ONAGm5V7P4AQ7w297f8xS0zaYzvuCOkIK7df30x13oRgI3m9+zklIy0iWe3dbZwfbup5Wq0pXujPacE37n/YhS4kCtfCjGPq3gIt+t6yiTVHzF7TUyk22WriWOn5S0s0sijEugez1dyqEhE3KwSFixRi6Gur56hY0vt2P2cZSlFDDrp7hsS60dgAAhxD/OblyexosWEvy7Ho+1BU2xb7nnX9vMLg7Rn1SF6X9EbEMRHQP9x5MlgwLeJCKNt6R6cLgODDROrbdjlyPs5Xa6PGzHwJ+dnWItFO4OZoEGsDpCPLFLDZIykZasS1QQYeIyuS+wtSwumiWbptBAbG88DtRXy2qIl52rZm+GtFrhvrtKtHrG7b8yzk+qqNyuravUcvsu0ZA0yBXCZc2qwzA08inj998KPQ58bdGGPTNJT6D2TH2lkJ4AGYIs9DCJttKwT0M5WsoXQteMJ3NmYtzAnKkTo4EV50flbs3PXWRXt0uFt54cGKQ34G6bUcjuT8ErLoCKnlXEOKVk65xoK07vJ339qvHZ0U3Z0fokxAUH8DtSORlJlaaqMbPj0r1K0y9I3RGddEhic=
    app: kayle7777
